### ISSUE TITLE
New Search: Course Over Time Part One and Part Two

### ISSUE THREAD

**Issue by Yunhao-Luo** [ucsb-cs156-f22/f22-6pm-courses#44]
* PART ONE: Service that gets data from MongoDB database. Make a service, similar to the UCSBCurriculumService, but instead of doing API calls, do MongoDB queries. Write tests. You need a method that takes a start quarter, end quarter, and a course id, and returns a list of ConvertedSections.

* PART TWO: Backend controller method: Write a backend controller method (unauthenticated GET) that takes a start quarter, end quarter, and a course id, and returns a list of Converted Sections. This is just wrapping a backend controller route around the service developed in Part one.

**Comment by pconrad** [comment]
This PR was closed by accident; reopening.
